---
- hosts: local
  tasks:
    - apt: pkg=openjdk-6-jdk state=present
    - git: repo=git@github.com:edtell/founders.git dest /tmp/founders
    - get_url: url=http://www.interior-dsgn.com/apache/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz dest=/tmp